version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: crmintapp
      MYSQL_USER: crmintapp
      MYSQL_PASSWORD: crmintapp
    volumes:
      - db_data:/var/lib/mysql

  backends:
    build:
      context: .
      dockerfile: docker/backends/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      DATABASE_URI: mysql+mysqldb://crmintapp:crmintapp@db:3306/crmintapp
    volumes:
      -  ./backends:/app/backends
    depends_on:
      - db
      - migrations
      - seeds

  migrations:
    build:
      context: .
      dockerfile: docker/backends/Dockerfile
    environment:
      DATABASE_URI: mysql+mysqldb://crmintapp:crmintapp@db:3306/crmintapp
    command: >
      bash -c "export PYTHONPATH="/root/google-cloud-sdk/platform/google_appengine:lib" &&
               export FLASK_APP=run_ibackend.py &&
               export FLASK_DEBUG=1 &&
               export APPLICATION_ID=crmintapp &&
               cd /app/backends &&
               python -m flask db upgrade"
    depends_on:
      - db

  seeds:
    build:
      context: .
      dockerfile: docker/backends/Dockerfile
    environment:
      DATABASE_URI: mysql+mysqldb://crmintapp:crmintapp@db:3306/crmintapp
    command: >
      bash -c "export PYTHONPATH="/root/google-cloud-sdk/platform/google_appengine:lib" &&
               export FLASK_APP=run_ibackend.py &&
               export FLASK_DEBUG=1 &&
               export APPLICATION_ID=crmintapp &&
               cd /app/backends &&
               python -m flask db_seeds"
    depends_on:
      - db
      - migrations

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backends

volumes:
  db_data:
